---
- name: Get Gather Facts from Remote Hosts
  gather_facts: True
  hosts: all
  
  tasks:
    - name: Get date for filename
      set_fact: date="{{ ansible_date_time.date }}"
      run_once: true
      
    - name: ''
      set_fact: 
        ip: "{{ ansible_host }}"

#    - name: 'Change ssh port to 5986'
#      set_fact:
#        ansible_port: 5986

    - name: Gather Ansible Facts About Host
      setup:
        gather_subset:
          - all
    - debug: 
        msg: "{{ ansible_facts }}"
        
    - set_fact:
        result_path: "/var/report/gf_widow"
        result_file: "/var/report/gf_widow/server_facts.csv"
        porti: "22"
    - name: " Create dir master node"
      file:
        path: "{{ result_path }}"
        recurse: yes
        state: directory
        mode: '0777'
      delegate_to: localhost
      ignore_errors: true
        
    - name: Create CSV
      copy: 
        content: "{{ all_results }}"
        dest: "{{ result_file }}"
      delegate_to: localhost
      no_log: true
      run_once: true
      tags: always

