---
- name: Get Gather Facts from Remote Hosts
  gather_facts: True
  hosts: all
  
  tasks:
    - name: Get date for filename
      set_fact: date="{{ ansible_date_time.date }}"
      run_once: true
      
    - name: ''
      set_fact: 
        ip: "{{ ansible_host }}"

#    - name: 'Change ssh port to 5986'
#      set_fact:
#        ansible_port: 5986

    - name: Gather Ansible Facts About Host
      setup:
        gather_subset:
          - all
    - debug: 
        msg: "{{ ansible_facts }}"
        
    - set_fact:
        result_path: "/var/report/gf_widow"
        result_file: "/var/report/gf_widow/server_facts.csv"
        porti: "22"
        
    - name: " Create dir master node"
      file:
        path: "{{ result_path }}"
        recurse: yes
        state: directory
        mode: '0777'
      delegate_to: localhost
      ignore_errors: true
    
    - name: "PowerShell Helix Ultra"
      win_command: net users
      register: net_user
    - debug:
        msg: "{{ net_user }}"
        
#    - name: Create CSV
#      copy: 
#        content: |
#          {% for host in ansible_play_hosts %}
#          | {{ hostvars[host].nodename }} | {{ hostvars[host].domain }} | {{ hostvars[host].windows_domain_member }} | {{ hostvars[host].windows_domain_role }} |  {{ hostvars[host].distribution }} | {{ hostvars[host].distribution_major_version }} | {{ hostvars[host].distribution_version }} | {{ hostvars[host].architecture }} | {{ hostvars[host].bios_date }} | {{ hostvars[host].bios_version }} | {{ hostvars[host].connection_name }} | {{ hostvars[host].interface_name }} | {{ hostvars[host].ipv4_address }} | {{ hostvars[host].ipv6_address }} | {{ hostvars[host].default_gateway }} | {{ hostvars[host].mac_address }} | {{ hostvars[host].lastboot }} | {{ hostvars[host].reboot_pending }} | {{ hostvars[host].uptime }} | {{ hostvars[host].machine_id }} | {{ hostvars[host].total_memory }} | {{ hostvars[host].processor }} | {{ hostvars[host].processor_cores }} | {{ hostvars[host].processor_count }} | {{ hostvars[host].product_name }} |
#          {% endfor %}
#        dest: "{{ result_file }}"
#      delegate_to: localhost    
#      run_once: true

